# -----------------------------------------------------------------------------
# Archivo de configuración para despliegue en Render.com
# Define la arquitectura del servicio web, configuración y variables de entorno
# -----------------------------------------------------------------------------

services:
  # Definición de servicio web para la plataforma de frameworks de prompt engineering
  - type: web                               # Tipo de servicio: web app con endpoint público
    name: prompt-engineering-frameworks     # Identificador único del servicio en Render
    env: python                             # Entorno de ejecución basado en Python
    buildCommand: pip install -r requirements.txt  # Comando ejecutado durante la fase de build
    startCommand: sh render.sh              # Script que inicia el servicio tras el build
    
    # Configuración de variables de entorno para el servicio
    envVars:
      - key: FLASK_SECRET_KEY               
        generateValue: true                 # Render genera automáticamente un valor seguro único
      - key: OPENAI_API_KEY                 
        sync: false                         # API key no sincronizada entre deployments (se configura manualmente)
      - key: RESEND_API_KEY
        sync: false                         # API key para el servicio de envío de correos
      - key: EMAIL_FROM
        value: "info@promptagent.info"      # Dirección de correo remitente
      - key: EMAIL_TO
        value: "contacto@promptagent.info"  # Dirección de correo destinatario
      - key: PORT
        value: "10000"                      # Puerto en el que se ejecutará la aplicación
      - key: FLASK_ENV
        value: "production"                 # Entorno de ejecución (production/development)
      - key: PROMO_CODE1
        sync: false                         # Código promocional 1 (no sincronizado por seguridad)
      - key: PROMO_CODE2
        sync: false                         # Código promocional 2 (no sincronizado por seguridad)
    
    healthCheckPath: /                      # Endpoint para verificar que el servicio está operativo
    autoDeploy: true                        # Despliegue automático cuando hay cambios en la rama principal
